export default [
  {
    label: "电商相关",
    list: [
      "iconfont zmt-haiguan", // 海关
      "iconfont zmt-dianshang", // 电商
      "iconfont zmt-jianguan", // 监管
      "iconfont zmt-baoshuishuie", // 保税
      "iconfont zmt-gangkou", // 港口
      "iconfont zmt-haiwaicang1", // 海外仓
      "iconfont zmt-z049", // 行政纠纷
      "iconfont zmt-zixun1", // 资讯
      "iconfont zmt-pinpaishouquanshijian", // 品牌授权
      "iconfont zmt-shangbiaozhuce", // 商标注册
      "iconfont zmt-tuiguangguanggaowei", // 广告推广
      "iconfont zmt-555", // 代运营
      "iconfont zmt-tongguan", // 通关
      "iconfont zmt-tongguantuishui", // 通关退税
      "iconfont zmt-apec", // APEC
    ]
  }, {
    label: "常用图标",
    list: [
      "iconfont zmt-zhiwen",
      "iconfont zmt-yulebao",
      "iconfont zmt-zhibo",
      "iconfont zmt-youhuiquan",
      "iconfont zmt-WIFI",
      "iconfont zmt-yanchu",
      "iconfont zmt-yinhangka",
      "iconfont zmt-yixiangkan",
      "iconfont zmt-zengjia",
      "iconfont zmt-yuyin",
      "iconfont zmt-yingchengka",
      "iconfont zmt-xiaomi",
      "iconfont zmt-xiaojuchang",
      "iconfont zmt-xiaoxi",
      "iconfont zmt-shoucang",
      "iconfont zmt-xiaoshi",
      "iconfont zmt-xiazai",
      "iconfont zmt-xiangkan",
      "iconfont zmt-xiaoxizhongxin",
      "iconfont zmt-wode",
      "iconfont zmt-xiangji",
      "iconfont zmt-shuaxin",
      "iconfont zmt-weibo",
      "iconfont zmt-tishi",
      "iconfont zmt-tuipiao",
      "iconfont zmt-shouji",
      "iconfont zmt-tupian",
      "iconfont zmt-weixin",
      "iconfont zmt-taolunqu",
      "iconfont zmt-sousuo",
      "iconfont zmt-shuju",
      "iconfont zmt-saoyisao",
      "iconfont zmt-shangchuan",
      "iconfont zmt-shibai",
      "iconfont zmt-shengyinguanbi",
      "iconfont zmt-shouye",
      "iconfont zmt-shijian",
      "iconfont zmt-shezhi",
      "iconfont zmt-shandian",
      "iconfont zmt-shequ",
      "iconfont zmt-shengyin",
      "iconfont zmt-shangquan",
      "iconfont zmt-lipinka",
      "iconfont zmt-shaixuan",
      "iconfont zmt-pinglun",
      "iconfont zmt-qupiao",
      "iconfont zmt-shanchu",
      "iconfont zmt-pengyouquan",
      "iconfont zmt-rili",
      "iconfont zmt-paihangbang",
      "iconfont zmt-mima",
      "iconfont zmt-lihe",
      "iconfont zmt-nv",
      "iconfont zmt-nan",
      "iconfont zmt-jianshao",
      "iconfont zmt-ditu",
      "iconfont zmt-gongyi",
      "iconfont zmt-dingwei",
      "iconfont zmt-kabao",
      "iconfont zmt-dingdan",
      "iconfont zmt-hongbao",
      "iconfont zmt-dianying",
      "iconfont zmt-fuzhi",
      "iconfont zmt-huati",
    ]
  }, {
    label: "其他图标",
    list: [
      "iconfont zmt-wenjianjia1",
      "iconfont zmt-wodewenzhang",
      "iconfont zmt-shoushi",
      "iconfont zmt-dangan11",
      "iconfont zmt-dingdan2",
      "iconfont zmt-fabu2",
      "iconfont zmt-yingyongshangdian",
      "iconfont zmt-jiedianguanli1",
      "iconfont zmt-jiqunguanli",
      "iconfont zmt-zhibiao1",
      "iconfont zmt-jingxiang",
      "iconfont zmt-zuhuguanli",
      "iconfont zmt-kehuduan",
      "iconfont zmt-zhiwei",
      "iconfont zmt-kemu",
      "iconfont zmt-luyouqi1",
      "iconfont zmt-diqu",
      "iconfont zmt-biaodan",
      "iconfont zmt-dangan1",
      "iconfont zmt-zhibiao",
      "iconfont zmt-tongzhi",
      "iconfont zmt-yixiangjinguanli_yixiangjinjiezhuan",
      "iconfont zmt-zhishi",
      "iconfont zmt-fabu11",
      "iconfont zmt-icon-2",
      "iconfont zmt-icon-38",
      "iconfont zmt-icon-37",
      "iconfont zmt-icon-36",
      "iconfont zmt-icon-35",
      "iconfont zmt-icon-34",
      "iconfont zmt-icon-33",
      "iconfont zmt-icon-32",
      "iconfont zmt-icon-31",
      "iconfont zmt-icon-30",
      "iconfont zmt-icon-1",
      "iconfont zmt-icon-28",
      "iconfont zmt-yunjisuan-",
      "iconfont zmt-xiatian-",
      "iconfont zmt-wuliupeisong-1",
      "iconfont zmt-wuliupeisong-",
      "iconfont zmt-wangluo-15",
      "iconfont zmt-tongxin-8",
      "iconfont zmt-wangluo-10",
      "iconfont zmt-wangluo-9",
      "iconfont zmt-wangluo-8",
      "iconfont zmt-wangluo-7",
      "iconfont zmt-wangluo-6",
      "iconfont zmt-jinrong-",
      "iconfont zmt-jiaoyu-31",
      "iconfont zmt-anquan-3",
      "iconfont zmt-shuju5",
      "iconfont zmt-xitongpeizhi1",
      "iconfont zmt-shujuzichanfaxianrenwu",
      "iconfont zmt-mulu1",
    ]
  }
]